<?php
//echo $block->ViewAction();
//echo "prashant gautam";
?>
<!-- <div class="prashant">hiiiii</div> 
<img src="<?php //echo $block->getImageUrl(); ?>" alt="Italian Trulli">-->
<div class="conatiner-fluid homepage_content">
		<h1 class="heading">Welcome to Dropbyy</h1>
	<div class="hb-main">
		<div class="hb-left">
	<div class="row">
		<h1 class="heading">Welcome to Dropbyy</h1>
		<div class="col-md-9">
			<p class="wordrap">Welcome to Dropbyy  Your convenience store headquarters!
				At Dropbyy our valued consumer receives the convenience without “Outrageously High Prices!” We stride to offer products at the lowest prices possible and when possible, well pass on the wholesale buys!
				<br/>
				We understand how important personal hygiene is. Which is why, we have selected the most reliable brands for you to choose from. Winery direct, scotch care, deos, perfumes, powders, creams, lotions, cigertaes, sanitary products, shaving essentials, common pharma and wellness products.
				We believe JUUL is the first viable alternative for adult smokers. 
				Smoking is bad for your health, and those who don’t currently use nicotine products should not start.
				We share public health concerns about cigarettes; in fact, they constitute our company’s mission.
				<br/>
				If you share our concerns and would like to speak with someone at JUUL, please contact youthprevention@juul.com.
			</p>
		</div>
		<div class="hb-right">
			<div class="juul_product"><label>Alternative for adult smokers</label>
				<p class="imagecss" style="border-style: double;"><img class="sidebar" src="<?php echo $block->getImageUrl(); ?>" alt="We also offer" /></p>
			</div>
		</div>
			</p>
		</div>
		<div class="col-md-3">
			<p><img class="sidebar" src="<?php echo $block->getImageUrl(); ?>" alt="We also offer" /></p>
		</div>
	</div>
</div>

