<div class="hbr-main pad-main">
<div class="block-title-main">
<h2>We also Offer</h2>
<div class="title-border"></div>
</div>
<div class="hbr-main">
<div style="margin: 0 -10px;">
<div class="hbr-content hbr-slider">
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/weoffer.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/imperial.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/king.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/scotch.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/oldliq.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/whitePills.jpg"}}" alt="img-232-86" /> </a></div>
<div class="hbr-inner"><a href="#"> <img class="img-resp center-b" src="{{media url="wysiwyg/home/madira.jpg"}}" alt="img-232-86" /> </a></div>
</div>
</div>
<script type="text/javascript" xml="space">// <![CDATA[
            require(['jquery', 'cpowlcarousel'], function ($) {
                $(document).ready(function () {
                    $(".hbr-slider").owlCarousel({
                        items: 5,
                        itemsDesktop: [1080, 4],
                        itemsDesktopSmall: [860, 3],
                        itemsTablet: [768, 3],
                        itemsTabletSmall: [639, 3],
                        itemsMobile: [479, 2],
                        pagination: true,
                         autoPlay: 3000,
                        navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                        navigation: true,
                    });
                });
            });
// ]]></script>
</div>
</div>